# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 565305a5a1feda9e25ee6e6fe4370c018bbf7f9f09b04f5d2e855c0f40450cf33fe8d77c1bc46a7b74f71eb6cd124b1b8fa51b34bdf44ebf2f1a791e7182100b

test:
  secret_key_base: 7854d4feff0087ae1a49f3b46267ad257a420c4739f47016315726d35a2201d462fa89045c862e8f74abe428673e42f51cdf6b70ee1fc1b7858ece27c419e8d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
